### ISSUE TITLE
Bower install problem

### ISSUE THREAD

**Issue by antoniocapelo** [Jxck/assert#14]
Hi there,

When running bower install https://github.com/Jxck/assert the bower package that's being downloaded just has a 'index' file which replicates the github repository page. I've checked your bower.json and it seems OK, but something must be broke..

**Comment by jeffmcmahan** [comment]
@Jxck, if you're not going to publish to bower, could you change the directions to include /assert.js at the end of the URL? Most people are probably getting the same results as @antoniocapelo, and saying forget it.

**Comment by Jxck** [comment]
> @Jxck, if you're not going to publish to bower

I wanna publish to bower but @jgallen takes that namespace with fork of this repo https://github.com/jgallen23/assert

so using that and telling him to merge my update will work in standard bower way.

**Comment by Jxck** [comment]
FYI #19
